name: Python Lint & Linter Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3️⃣ Install dependencies
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint

    # 4️⃣ Run flake8
    - name: Run flake8
      run: |
        echo "🔍 Running flake8..."
        flake8 .

    # 5️⃣ Run pylint
    - name: Run pylint
      run: |
        echo "🔍 Running pylint..."
        pylint **/*.py || true
